apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32345
  type: NodePort