version: "3.9"
services:

  db:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: 'mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  gateway:
    build:
     context: "../S6-gateway/"
     dockerfile: "Dockerfile"
    hostname: gateway
    container_name: gateway
    restart: "on-failure"
    ports:
      - "8083:8083"
    environment:
      - spring.cloud.gateway.routes[0].id=userapi
      - spring.cloud.gateway.routes[0].uri=http://user-service:8081/
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
    depends_on:
      - db

  user-service:
    build:
      context: "../S6-userapi/"
      dockerfile: "Dockerfile"
    hostname: user-service
    container_name: user-service
    restart: "on-failure"
    ports:
      - "8081:8081"
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysql
     - SPRING_DATASOURCE_USERNAME=root
     - SPRING_DATASOURCE_PASSWORD=password
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
      - gateway

  frontend-gateway:
    build:
      context: "../S6-frontend/"
      dockerfile: "Dockerfile"
    hostname: frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - user-service

volumes:
  my-db: