version: "3.9"
services:

  db:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: 'mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  subreddit-db:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: 'mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3305:3306'
    expose:
      # Opens port 3305 on the container
      - '3305'
      # Where our data will be persisted
    volumes:
      - subreddit-db:/var/lib/mysql

  gateway:
    build:
     context: "../S6-gateway/"
     dockerfile: "Dockerfile"
    hostname: gateway
    container_name: gateway
    restart: "on-failure"
    ports:
      - "8083:8083"
    environment:
      - spring.cloud.gateway.routes[0].id=userapi
      - spring.cloud.gateway.routes[0].uri=http://user-service:8081/
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
      - spring.cloud.gateway.routes[1].id=subredditapi
      - spring.cloud.gateway.routes[1].uri=http://subredditapi-service:8086/
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/subreddit/**
    depends_on:
      - db

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_lOGIN=yes

  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9200:9200"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db
      DB_DATABASE: mysql
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    restart: "on-failure"
    ports:
      - 8180:8080
    depends_on:
      - db

  user-service:
    build:
      context: "../S6-userapi/"
      dockerfile: "Dockerfile"
    hostname: user-service
    container_name: user-service
    restart: "on-failure"
    ports:
      - "8081:8081"
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysql
     - SPRING_DATASOURCE_USERNAME=root
     - SPRING_DATASOURCE_PASSWORD=password
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
     - SPRING_KAFKA_BOOTSTRAP-SERVERS=http://kafka:9092
    depends_on:
      - db
      - gateway

  subredditapi-service:
    build:
      context: "../subreddit/"
      dockerfile: "Dockerfile"
    hostname: subreddit-service
    container_name: subreddit-service
    restart: "on-failure"
    ports:
      - "8086:8086"
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://subreddit-db:3306/mysql
     - SPRING_DATASOURCE_USERNAME=root
     - SPRING_DATASOURCE_PASSWORD=password
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
     - SPRING_KAFKA_BOOTSTRAP-SERVERS=http://kafka:9092
    depends_on:
      - subreddit-db

  frontend-gateway:
    build:
      context: "../S6-frontend/"
      dockerfile: "Dockerfile"
    hostname: frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - subredditapi-service
      - user-service

volumes:
  my-db:
  subreddit-db: