apiVersion: apps/v1
kind: Deployment
metadata:
  name: subredditapi
  labels:
    app: subredditapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subredditapi
  template:
    metadata:
      labels:
        app: subredditapi
    spec:
      containers:
        - name: userapi
          image: localhost:5000/subredditapi:v0.1
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3307/mysql
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update