apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: lucvdzandt/gateway:latest
          ports:
            - containerPort: 8083
          env:
            - name: spring_cloud_gateway_routes_0_id
              value: userapi
            - name: spring_cloud_gateway_routes_0_uri
              value: http://userapi-service:8081
            - name: spring_cloud_gateway_routes_0_predicates_0_
              value: Path=/user/**
