apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
  labels:
    app: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - name: sql
          image: mysql:latest
          ports:
            - containerPort: 3003